import {
  bleach,
  black_clover,
  dragon_ball,
  jujutsu_kaisen,
  fma_brotherhood,
  naruto,
  gintama,
  one_piece,
  demon_slayer,
  attack_on_titan,
  hunter_x_hunter,
  boku_no_hero_academia,
} from "@/public/animes";

export const data = [
  {
    id: "1",
    name: "bleach",
    image: bleach,
    kind: "TV",
    episodes: 366,
    episodes_aired: 366,
    score: "7.92",
  },
  {
    id: "2",
    name: "black_clover",
    image: black_clover,
    kind: "TV",
    episodes: 170,
    episodes_aired: 170,
    score: "7.16",
  },
  {
    id: "3",
    name: "dragon_ball",
    image: dragon_ball,
    kind: "TV",
    episodes: 153,
    episodes_aired: 153,
    score: "8.68",
  },
  {
    id: "4",
    name: "jujutsu_kaisen",
    image: jujutsu_kaisen,
    kind: "TV",
    episodes: 24,
    episodes_aired: 24,
    score: "8.78",
  },
  {
    id: "5",
    name: "fma_brotherhood",
    image: fma_brotherhood,
    kind: "TV",
    episodes: 64,
    episodes_aired: 64,
    score: "9.24",
  },
  {
    id: "6",
    name: "naruto",
    image: naruto,
    kind: "TV",
    episodes: 220,
    episodes_aired: 220,
    score: "8.3",
  },
  {
    id: "7",
    name: "gintama",
    image: gintama,
    kind: "TV",
    episodes: 367,
    episodes_aired: 367,
    score: "9.0",
  },
  {
    id: "9",
    name: "one_piece",
    image: one_piece,
    kind: "TV",
    episodes: 1030,
    episodes_aired: 1030,
    score: "8.58",
  },
  {
    id: "10",
    name: "demon_slayer",
    image: demon_slayer,
    kind: "TV",
    episodes: 26,
    episodes_aired: 26,
    score: "8.6",
  },
  {
    id: "11",
    name: "attack_on_titan",
    image: attack_on_titan,
    kind: "TV",
    episodes: 75,
    episodes_aired: 75,
    score: "9.16",
  },
  {
    id: "12",
    name: "hunter_x_hunter",
    image: hunter_x_hunter,
    kind: "TV",
    episodes: 148,
    episodes_aired: 148,
    score: "9.1",
  },
  {
    id: "13",
    name: "boku_no_hero_academia",
    image: boku_no_hero_academia,
    kind: "TV",
    episodes: 114,
    episodes_aired: 114,
    score: "8.39",
  },
];
